GET {{HostAddress}}/beer/
Accept: application/json

###

POST {{HostAddress}}/beer/
Content-Type: application/json

{
    "name": "Eichhof Braugold",
    "alcoholByVolume": 0.052
}

###

DELETE {{HostAddress}}/beer/Eichhof%20Braugold
